PhoneBook
Strandol/javascript-task-2 pull request #2
Opened 2017-01-29 23:21 UTC by Strandol

2017-01-29 23:22 UTC, Strandol commented
@DudaGod Го проверять )

2017-01-30 06:06 UTC, DudaGod commented
го го го, все фигня - переделать!!!111
Шучу, вечером гляну =)

2017-01-30 18:02 UTC, DudaGod commented on phone-book.js
> +    if (phone.match(/\d{10}/) && !isNoteExists(phone) && name) {
давай регексп напишем с использованием ^ и $. Т.е. начала и конца строки, потому что такая строка сейчас тоже прокатит - `abc1234567890dkdkd`

2017-01-30 19:23 UTC, DudaGod requested changes

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +    if (phone.match(/\d{10}/) && !isNoteExists(phone) && name) {
Дальше `!isNoteExists(phone)` - во первых функцию правильно назвать `isNotExists`. Затем двойное отрицание. Мало того, что функция уже в своем название содержит отрицание так ты его еще и инвертируешь. Не проще просто написать функцию - `isExist` которая будет делать тоже самое?

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +    return false;
опять у тебя эта проблема, ты же уже в `if` условие добавил, которое уже итак булевское. Так просто верни его и результат будет тот же:
```js
return phone.match(/\d{10}/) && !isNoteExists(phone) && name;
```

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +    }
так давай вместо обычного for-а ты здесь юзнешь один из методов массива, который сделает это намного лучше. Подумай какой.

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +    }
в итоге можно будет просто его результат вернуть

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +function isNoteExists(phone) {
давай эту функцию в isExists переделаем

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +function isInfoCorrect(phone, name) {
а эту функцию давай переделаем в `isValid` - так понятнее будет. И обычно так функции валидации и называют

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
>  exports.isStar = true;
давай тут сразу перечислим все функции которые будем экспортить:
```js
exports.add = add;
exports.update = update;
...
```

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
>   */
а тут укажем в константы регекспы, которыми будем определять правильно ли задан телефон, мейл и т.д.
Например имя можно было бы так задать:
```js
var REGEXP_NAME = /^([a-zа-яё0-9]+\s?)+[^\s]$/i;
```

Т.е. в этом случае засчет плюсика имя может быть - "Bill Flin" например

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
>   */
круто было бы и для остальных написать регекспы (хоть это в задаче и не указано)

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +    }
тебе эта проверка тут не нужна просто записывай в поле, если запишется `undefined` ничего страшного не произойдет. Или можешь в самом конструкторе вот так указать:
```js
var Person = function (phone, name, email || null) {}
```
по идеи должно работать

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +    }
Давай еще в класс `Person` добавим методов. Которые тебе нужно записать в его прототип.
Например можно для каждого его поля добавить setter и getter. Тогда тебе легко можно будет изменять его поля.

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +var phoneBook = {
давай `phoneBook` сделаем тоже классом. У которого будет поле - `this.personsInfo = []`.
И в его прототип можно будет добавить методы: `addPerson`, `removePerson`, `updatePerson`, `getPerson` - который будет возвращать человека по индексу например и т.д.

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +var phoneBook = {
А экспортируемые функции - `add`, `update` и т.д. будут работать непосредственно с методами класса `phoneBook`.

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +    if (name && phone.match(/\d{10}/)) {
у тебя уже есть похожая проверка, можно кстати разбить на 3 метода: `isValidName`, `isValidPhone`, `isValidEmail`. А тут просто две из них юзнуть

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +    }
видишь вложенность глубокую? Ты же здесь можешь условие инвертировать и значительно уменьшить ее. Подумай как.

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +}
будет намного лучше если функция будет возвращать именно человека из книжки, а не индекс. Такой метод должен быть в классе `PhoneBook`

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +    }
подумай как можно красивее сделать используя методы Array

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +    return 0;
```js
return p1.name > p2.name ? 1 : -1;
```
результат такой же будет, но зато короче.

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +function getStrRepOfSortedInfo(info) {
название функции мягко говоря не очень )

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +function getConvertedPhoneNum(num) {
`beatifyPhoneNum`. Ты здесь не просто получаешь телефонный номер, ты его приводишь к красивому виду

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +    num.slice(3, 6) + '-' + num.slice(6, 8) + '-' + num.slice(8, 10);
в начале этой строки должен быть отступ

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +}
подумай как этот метод значительно упростить. Опять же методы из Array (подсказка). Ты практически везде юзаешь for

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +            resultInfo.push(new Person(pInfo.phone, pInfo.name, pInfo.email));
у тебя тут новый `Person` не должен создаваться - это же метод `find`, он должен найти уже существующий в `PhoneBook`

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +    resultInfo = resultInfo.sort(sortPersonInfoByName);
второй раз сортируешь тем же самым методом, подумай как его юзнуть один раз

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +    for (var field in info) {
тут нужно проверять с помощью `hasOwnProperty`. И напиши в коменте чем он отличается от `for in`

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +        if (exports.add(person.phone, person.name, person.email) ||
так плохо функции через `exports` вызывать. Подумай как можно сделать так, чтобы вызывать их напрямую

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +    for (var i = 0; i < csv.length; i++) {
опять for неожиданно

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +        person = new Person(parsedStr[1], parsedStr[0], parsedStr[2]);
ты тут должен проверить, что запись есть с помощью `find` прежде чем созадвать нового `Person`-а. Который вообще то должен создаваться в методе.
А после того как проверил - решаешь добавлять новый или обновлять существующий

2017-01-30 19:23 UTC, DudaGod commented on phone-book.js
> +    return amountOfAddedInfo;
в итоге это число будет равно кол-ву итераций по массиву, по этому вопросу нужно ли отдельная переменная по которой мы итерируемся?

2017-01-30 19:26 UTC, Strandol commented on phone-book.js
> +    if (phone.match(/\d{10}/) && !isNoteExists(phone) && name) {
@DudaGod Note - запись

2017-01-30 19:26 UTC, Strandol commented on phone-book.js
> +    if (phone.match(/\d{10}/) && !isNoteExists(phone) && name) {
@DudaGod Тут не not подразумевалось

2017-01-30 19:37 UTC, Strandol commented on phone-book.js
> +    for (var field in info) {
@DudaGod В смысле чем? **hasOwnProperty** - проверка на существование свойства - а **for in** это уже цикл

2017-01-30 19:38 UTC, Strandol commented on phone-book.js
> +    return amountOfAddedInfo;
@DudaGod Нет, посмотри же условия при которых переменная увеличивается, _add_ - возвращает true или false в зависимости от выполнения операции

2017-01-30 20:19 UTC, Strandol commented on phone-book.js
>  exports.isStar = true;
@DudaGod `eslint `ругнулся что не определили эти переменные в начале еще, выписал их и определил в конце

2017-01-30 20:21 UTC, Strandol commented on phone-book.js
> +    }
@DudaGod `Eslint `не позволяет писать аргументы таким образом function (phone, name, email || null), напишу иначе

2017-01-31 17:52 UTC, Strandol commented on phone-book.js
> +    resultInfo = resultInfo.sort(sortPersonInfoByName);
@DudaGod Сортируется один раз, первый раз сортируется - потом возврат функции, если нет то потом

2017-01-31 18:15 UTC, Strandol commented on phone-book.js
> +        person = new Person(parsedStr[1], parsedStr[0], parsedStr[2]);
@DudaGod Существует или нет, проверяется в методе add, моя проверка лишняя)

2017-02-01 22:43 UTC, DudaGod requested changes

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +var REGEXP_EMAIL = /^[a-z]+@[a-z]+.[a-z]+$/;
Кажется вот так будет правильнее работать:
```js
var REGEXP_EMAIL = /^[a-zа-яё0-9](\.?[a-zа-яё0-9-_]+)+@([a-zа-яё0-9][-_a-zа-яё0-9]+\.)+[a-zа-яё]{2,4}$/i;
```

разбери этот код в regex101

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +    this.email = email || '';
нафига тебе тут пустые строки? Просто присваивай. Обычно такую логику в конструктор не зашивают

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +    this.email = email || '';
и давай эти поля сделаем приватными. Обычно это так делается: `this._phone` Т.е. с помощью подчеркивания перед названием

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +    this.personsInfo = [];
здесь тоже давай сделаем это св-во класса приватным и назовем его `this._persons`. Итак понятно, что это будет массив человеков =)

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +    if (isInfoCorrect(person.getPhone(), person.getName(), person.getEmail()) &&
Давай переименуем в `isValidInfo` и будем ему передавать весь объект `person`. А внутри этого метода - `isValidInfo` уже вызывать `getPhone` и т.д. То есть можно избежать такого большого кол-во параметров

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +        !isNoteExists(person.getPhone())) {
ты видешь, что у тебя условие получается на 2 строки? Это очень плохо - нужно задуматься, как этого избежать.

И кажется функция должна называться `isPhoneExists`. Ты же именно его передаешь.
Так же предлагаю этот метод унести в класс `PhoneBook`, т.к. ты внутри используешь приватное св-во.

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +    return false;
я тебе разве про это не писал?
Инвертируй условие - тем самым уменьшишь вложенность.

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +        var person = this.personsInfo.find(function (elem) {
почему бы не завести метод `findByPhone`? Тогда тут можно будет значительно сократить код.

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +    if (isInfoCorrect(phone, name, email)) {
по условию `email` не обязателен

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +PhoneBook.prototype.getPerson = function (i) {
Этот метод должен называться - `getPersonByIndex`

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +var add = function (phone, name, email) {
почему через `var` объявил? А не через `function add()` ?

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +PhoneBook.prototype.removePerson = function (i) {
`removePersonByIndex`

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +    return false;
уже вроде писал, подумай как тут значительно уменьшить код, в итоге останется одна строка

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +    return !email || email.match(REGEXP_EMAIL);
это не правильная проверка. Отсутствие мыла не может быть валидным

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +}
это должно быть методом в PhoneBook

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +        resultInfo = phoneBook.personsInfo.slice(0);
ты тут не имеешь права так обходиться с приватным св-вом

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +        });
подумай еще раз, что тут больше подойдет?
Подумай над связкой `filter` + `map`

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +function sortPersonInfoByName(p1, p2) {
`sortPersonsByName`

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +    });
подумай как метод тут больше подойдет при использовании которого не нужен будет тебе объявление лишнего массива

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +function isInfoSuitForQuery(info, query) {
почему этот метод так далеко от своего места использования?

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +function isInfoSuitForQuery(info, query) {
`isPersonSuitesQuery`

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +        phoneBook.removePerson(phoneBook.personsInfo.indexOf(foundedInfo));
тебе этот метод звать не нужно если человек не найден

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +function findInfo(personNum) {
у тебя же уже есть такой метод

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +function convertToStartedRepPhone(phone) {
не понятно название, что еще за `Rep`?

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +var importFromCsv = function (csv) {
везде эти `var`-ы на `function` поменять не забудь

2017-02-01 22:43 UTC, DudaGod commented on phone-book.js
> +            update(parsedStr[1], parsedStr[0], parsedStr[2])) {
это фигня какая то.
Ты должен сначала проверить, что такая запись есть или нет, а уже после этого решать создавать новый или обновлять

2017-02-02 17:59 UTC, Strandol commented on phone-book.js
> +        !isNoteExists(person.getPhone())) {
@DudaGod Я проверяю не наличие телефона, а есть ли запись  с таким номером

2017-02-02 18:22 UTC, Strandol commented on phone-book.js
> +    return !email || email.match(REGEXP_EMAIL);
@DudaGod Может, в задании сказано, что можно передать без мыла

2017-02-02 18:23 UTC, Strandol commented on phone-book.js
> +    return !email || email.match(REGEXP_EMAIL);
@DudaGod 
Метод update для обновления записей:

На вход принимает «Телефон», «Имя» и «Электронную почту»
Обновляет «Имя» и «Электронную почту» по заданному «Телефону»
Возвращает true или false в зависимости от успеха опереации
«Электронную почту» можно стереть (не передав последний параметр), а «Имя» – нет

2017-02-02 18:24 UTC, Strandol commented on phone-book.js
> +    return !email || email.match(REGEXP_EMAIL);
@DudaGod Так же и остальные, могут принимать без мыла, мои тесты все прошли

2017-02-02 18:33 UTC, Strandol commented on phone-book.js
> +function sortPersonInfoByName(p1, p2) {
@DudaGod надо инфу сортировать а не людей!))

2017-02-02 19:20 UTC, Strandol commented on phone-book.js
> +        phoneBook.removePerson(phoneBook.personsInfo.indexOf(foundedInfo));
@DudaGod тут он по любому найдется )
просто мне нужный нужен

2017-02-02 19:21 UTC, Strandol commented on phone-book.js
> +            update(parsedStr[1], parsedStr[0], parsedStr[2])) {
@DudaGod Я же тебе отвечал, когда вызывается add - там идет проверка - существует или нет

2017-02-02 19:23 UTC, Strandol commented on phone-book.js
> +            update(parsedStr[1], parsedStr[0], parsedStr[2])) {
@DudaGod `add` и `update` - возвращают `boolean`

2017-02-02 19:34 UTC, DudaGod commented on phone-book.js
> +function sortPersonInfoByName(p1, p2) {
название слишком длинное получается итак будет же понятно, что ты сортируешь информацию о них, а не их настоящих людей переставляешь.

2017-02-03 04:30 UTC, DudaGod requested changes

2017-02-03 04:30 UTC, DudaGod commented on phone-book.js
> +    /^[a-zа-яё0-9](\.?[a-zа-яё0-9-_]+)+@([a-zа-яё0-9][-_a-zа-яё0-9]+\.)+[a-zа-яё]{2,4}$/i;
по другому разве никак не разбить? Имею ввиду чтобы на первой строке `REGEXP_EMAIL` была часть регулярки написана

2017-02-03 04:30 UTC, DudaGod commented on phone-book.js
> +        this.getAllInfo().push(person);
это я тебе такой метод предложил создать? Кажется что `this._persons.push(person)` читается понятнее

2017-02-03 04:30 UTC, DudaGod commented on phone-book.js
> +    if (!isValidInfo(new Person(phone, name, email))) {
ты же понимаешь что так не очень? То есть ты создаешь инстанс класса и передаешь его в функцию которая проверит, что он валиден. Если нет - то ты просто зря создал новый инстанс.

Да я помню, что такую функцию предложил я - которая принимала бы объект `Person`, чтобы метод `add` покороче был. Я забыл, что еще должна нормально вызываться и в других случаях. Жаль в JS нормальной перегрузки функций нет.

Давай все таки просто передавать три параметра и не парится.

2017-02-03 04:30 UTC, DudaGod commented on phone-book.js
> +    if (isValidInfo(person) && !this.isNoteExists(person.getPhone())) {
предлагаю в `isValidInfo` передавать все таки поля `person` как у тебя изначально было. Объяснения ниже написал.
Но давай хотя бы так напишем:

```js
var phone = person.getPhone();
var name = person.getName();
var email = person.getEmail();

if (isValidInfo(phone, name, email) && !this.isNoteExists(person.getPhone())) {....}
```

2017-02-03 04:30 UTC, DudaGod commented on phone-book.js
> +    }
```js
....
var person = this.findByPhone(phone);

if (!person) {
  return false;
}

person.setName(name);
person.setEmail(email || '');

return true;
```

Кажется так меньше вложенности.

2017-02-03 04:30 UTC, DudaGod commented on phone-book.js
> +};
Илья ты видишь, что у тебя функции `isNoteExists` и `findByPhone` абсолютно идентичны? Ты уверен, что нам нужно 2 одинаковые функции? Причем вторая `findByPhone` намного понятнее по названию. Может ее будем везде юзать?

2017-02-03 04:30 UTC, DudaGod commented on phone-book.js
> +function update(phone, name, email) {
не пойму по какому принципу ты расставил все остальные функции, которые вне классов.
Кажется логичнее было основные функции `add`, `update`, `find`, `findAndRemove`, `importFromCsv` - т.е. те функции которые указаны в задании и которые ты экспортишь в итоге поставить рядом. Например сразу после объявлений методов прототипа `PhoneBook`

2017-02-03 04:30 UTC, DudaGod commented on phone-book.js
> +        this.getAllInfo().push(person);
А все я вспомнил. Илья это же метод класса, как ты думаешь он можешь обратиться к своему приватному свойству без каких либо геттеров, которые тоже объявлены в этом же классе?

2017-02-03 04:30 UTC, DudaGod commented on phone-book.js
> +PhoneBook.prototype.getAllInfo = function () {
Илья это геттер, он должен называться очень похоже на название св-ва которое ты возвращаешь.
`getPersons` - вот так оно должно называться

2017-02-03 04:30 UTC, DudaGod commented on phone-book.js
> +function isPersonSuitesQuery(info, query) {
объявление этого метода должно быть выше (ближе к `find`)

2017-02-03 04:30 UTC, DudaGod commented on phone-book.js
> +function convertInfoToString(info) {
название функции обманывает. Я ожидаю, что ты переконвертишь к строке и вернешь. А ты возвращаешь ее массив строк на самом деле.

2017-02-03 04:30 UTC, DudaGod commented on phone-book.js
> +}
вместо этой функции я бы юзал регулярку + `replace` который я тебе в скайпе показывал

2017-02-03 04:30 UTC, DudaGod commented on phone-book.js
> +function getPhoneFromInfoStr(info) {
кстати и этот метод не нужен будет если заюзать крутые регулярки )

2017-02-03 04:30 UTC, DudaGod commented on phone-book.js
> +    csv = csv.split('\n');
обычно лучше параметр не перезаписывать.

2017-02-03 13:30 UTC, Strandol commented on phone-book.js
> +    /^[a-zа-яё0-9](\.?[a-zа-яё0-9-_]+)+@([a-zа-яё0-9][-_a-zа-яё0-9]+\.)+[a-zа-яё]{2,4}$/i;
@DudaGod Пробовал, у меня не получилось, `Eslint` ошибку выдает

2017-02-03 13:33 UTC, Strandol commented on phone-book.js
> +        this.getAllInfo().push(person);
@DudaGod Понял, может )
тут то да

2017-02-03 13:39 UTC, Strandol commented on phone-book.js
> +PhoneBook.prototype.getAllInfo = function () {
@DudaGod Точно, невнимательно я, не следую правилу DRY ))

2017-02-03 13:39 UTC, Strandol commented on phone-book.js
> +};
@DudaGod Точно, невнимательно я, не следую правилу DRY ))

2017-02-03 13:45 UTC, Strandol commented on phone-book.js
> +function convertInfoToString(info) {
@DudaGod Обманщик))

2017-02-03 13:47 UTC, Strandol commented on phone-book.js
> +function getPhoneFromInfoStr(info) {
@DudaGod Я не крутой еще )

2017-02-07 20:17 UTC, DudaGod approved these changes
в остальном /ok

2017-02-07 20:17 UTC, DudaGod commented on phone-book.js
> +    return this.getPersons().find(function (elem) {
это не `elem` - это `person`

2017-02-07 20:17 UTC, DudaGod commented on phone-book.js
> +PhoneBook.prototype.findByPhone = function (phone) {
а почему бы не назвать `getPersonByPhone`? У тебя выше есть методы с похожим названием

2017-02-07 20:17 UTC, DudaGod commented on phone-book.js
> +        resultInfo = phoneBook.getPersons().filter(function (elem) {
не `elem`, а `person` ты же знаешь, что перебираешь массив `persons`. Значит внутри коллбека пиши в единственном числе.

2017-02-07 20:17 UTC, DudaGod commented on phone-book.js
> +function getStringArrInfo(info) {
Давай эту функцию назовем `stringifyPersonsInfo`. Т.е. из названия сразу понятно, что информация о людях будет приводится к строке.

2017-02-07 20:17 UTC, DudaGod commented on phone-book.js
> +    return getStringArrInfo(resultInfo);
```js
return stringifyPersonsInfo(personsInfo.sort(sortPersonsByName));
```

2017-02-07 20:17 UTC, DudaGod commented on phone-book.js
> +        phoneBook.removePersonByIndex(phoneBook.getPersons().indexOf(foundedInfo));
```js
phoneBook.getPersons().indexOf(foundedInfo) // у тебя для этого вызова есть уже метод
```

2017-02-07 20:17 UTC, DudaGod commented on phone-book.js
> +}
чего не юзнул мой вариант с регулярками? =( Они же намного красивее обоих этих функций

2017-02-08 23:03 UTC, merged