Table
Strandol/javascript-task-2 pull request #3
Opened 2017-02-11 15:28 UTC by Strandol

2017-02-28 21:32 UTC, DudaGod commented on phone-book.js
> +var EMAIL_COL_LENGTH = 19;
Почему такие размеры?
А если у тебя есть имя  человека с длинной 25 символов? У тебя код перестанет правильно работать.
Давай напишем функцию которая будет для каждого из трех столбцов находить максимум. Она должна учитывать как слова в хедере таблицы, так и поля из книги

2017-02-28 21:35 UTC, DudaGod commented on phone-book.js
> +    var table = buildTopOfTable() + addDataIntoTable() + buildBottomOfTable();
так тебе придется постоянно фигачить переносы строк. Как вариант можно в каждой из функций вставлять несколько console.log-ов.

2017-02-28 21:39 UTC, DudaGod commented on phone-book.js
> +    return '\n\u{0250C}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}' +
вместо этой не читаемой строки давай юзать более понятные символы, отсюда - http://mnemoniki.tsymbal.su
Например такие:
╔═════════════════╗
║                 LOL                   ║
╠═════════════════║
║                 LOL                   ║
╚═════════════════╝
и т.д.

2017-02-28 21:41 UTC, DudaGod commented on phone-book.js
> +    return '\n\u{0250C}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}' +
почему то слова не перенес, фиг с ним.
И не забудь потом добавить скриншот, с получившейся таблицей

2017-02-28 21:42 UTC, Strandol commented on phone-book.js
> +    return '\n\u{0250C}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}' +
@DudaGod Хорошо, сделаю скрины

2017-02-28 21:43 UTC, Strandol commented on phone-book.js
> +    return '\n\u{0250C}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}' +
@DudaGod Что со словами? не понял

2017-02-28 21:44 UTC, DudaGod commented on phone-book.js
> +function addSpacesBetweenWordAndEnd(colLength, wordLength) {
название функции не должно быть такой длинной.
можно назвать, просто addSpaces.
А еще лучше чтобы этот метод дублировал переданный элемент указанное кол-во раз.
Есть кстати метод у String - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/repeat
Можешь подумать как написать нечто похожее

2017-02-28 21:47 UTC, DudaGod requested changes
жду исправлений. Сложно текущий код читать.

2017-02-28 21:51 UTC, DudaGod commented on phone-book.js
> +    return '\n\u{0250C}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}' +
я про свой пример. LOL должен был по центру отрисоваться.

2017-02-28 21:53 UTC, Strandol commented
@DudaGod постараюсь исправить

2017-02-28 21:54 UTC, Strandol commented on phone-book.js
> +    return '\n\u{0250C}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}\u{02500}' +
@DudaGod Еще подумал, чего так сделал))

2017-03-01 22:28 UTC, Strandol commented on phone-book.js
> +function addSpacesBetweenWordAndEnd(colLength, wordLength) {
@DudaGod Спасибо, не обращал внимание на этот метод)

2017-04-23 15:49 UTC, merged